# Use postgres/example user/password credentials
version: '3.1'

services:
  web:
    build: ./docker/nginx
    volumes:
    - ./out:/usr/share/nginx/html
    # - ./nginx/custom.conf:/etc/nginx/conf.d/custom.conf
    ports:
    - "80:80"
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
